import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import type {
  InferGetStaticPropsType,
  GetStaticProps,
  GetStaticPaths,
} from "next";
import Link from "next/link";
import { useMemo } from "react";
import getPeople, { url2id } from "../../../utils/util";
const inter = Inter({ subsets: ["latin"] });

export default function People({
  people,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  const listItems = useMemo(() => {
    return people.map((person) => (
      <li key={person.url}>
        <Link href={"/ssg/people/" + url2id(person.url)}>{person.name}</Link>
      </li>
    ));
  }, [people]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ol>{listItems}</ol>
      </main>
    </>
  );
}

export const getStaticProps = (async () => {
  const people = await getPeople();
  return { props: { people } };
}) satisfies GetStaticProps<{
  people: Person[];
}>;
